
package pe.com.ubicuo.eai.ebs.services.springtypebdws.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SpringTypeBDWSWSService", targetNamespace = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/ws", wsdlLocation = "/WEB-INF/wsdl/SpringTypeBDWS.wsdl")
public class SpringTypeBDWSWSService
    extends Service
{

    private final static URL SPRINGTYPEBDWSWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SPRINGTYPEBDWSWSSERVICE_EXCEPTION;
    private final static QName SPRINGTYPEBDWSWSSERVICE_QNAME = new QName("http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/ws", "SpringTypeBDWSWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("file:/D:/WorkSpaces/12c/SpringTypeBDWS/WebContent/WEB-INF/wsdl/SpringTypeBDWS.wsdl");
              url = pe.com.ubicuo.eai.ebs.services.springtypebdws.ws.SpringTypeBDWSWSService.class.getResource("/WEB-INF/wsdl/SpringTypeBDWS.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        SPRINGTYPEBDWSWSSERVICE_WSDL_LOCATION = url;
        SPRINGTYPEBDWSWSSERVICE_EXCEPTION = e;
    }

    public SpringTypeBDWSWSService() {
        super(__getWsdlLocation(), SPRINGTYPEBDWSWSSERVICE_QNAME);
    }

    public SpringTypeBDWSWSService(URL wsdlLocation) {
        super(wsdlLocation, SPRINGTYPEBDWSWSSERVICE_QNAME);
    }

    public SpringTypeBDWSWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns SpringTypeBDWSPortType
     */
    @WebEndpoint(name = "SpringTypeBDWSPort11SB")
    public SpringTypeBDWSPortType getSpringTypeBDWSPort11SB() {
        return super.getPort(new QName("http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/ws", "SpringTypeBDWSPort11SB"), SpringTypeBDWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpringTypeBDWSPortType
     */
    @WebEndpoint(name = "SpringTypeBDWSPort11SB")
    public SpringTypeBDWSPortType getSpringTypeBDWSPort11SB(WebServiceFeature... features) {
        return super.getPort(new QName("http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/ws", "SpringTypeBDWSPort11SB"), SpringTypeBDWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SPRINGTYPEBDWSWSSERVICE_EXCEPTION!= null) {
            throw SPRINGTYPEBDWSWSSERVICE_EXCEPTION;
        }
        return SPRINGTYPEBDWSWSSERVICE_WSDL_LOCATION;
    }

}
