
package pe.com.ubicuo.eai.ebs.services.springtypebdws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import pe.com.ubicuo.eai.ebs.services.springtypebdws.types.ConsultarPersonaRequest;
import pe.com.ubicuo.eai.ebs.services.springtypebdws.types.ConsultarPersonaResponse;
import pe.com.ubicuo.eai.ebs.services.springtypebdws.types.InsertarPersonaRequest;
import pe.com.ubicuo.eai.ebs.services.springtypebdws.types.InsertarPersonaResponse;
import pe.com.ubicuo.eai.ebs.services.springtypebdws.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SpringTypeBDWSPortType", targetNamespace = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpringTypeBDWSPortType {


    /**
     * 
     * @param request
     * @return
     *     returns pe.com.ubicuo.eai.ebs.services.springtypebdws.types.InsertarPersonaResponse
     */
    @WebMethod(action = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/insertarPersona")
    @WebResult(name = "InsertarPersonaResponse", targetNamespace = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/types", partName = "response")
    public InsertarPersonaResponse insertarPersona(
        @WebParam(name = "InsertarPersonaRequest", targetNamespace = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/types", partName = "request")
        InsertarPersonaRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns pe.com.ubicuo.eai.ebs.services.springtypebdws.types.ConsultarPersonaResponse
     */
    @WebMethod(action = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/consultarPersona")
    @WebResult(name = "ConsultarPersonaResponse", targetNamespace = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/types", partName = "response")
    public ConsultarPersonaResponse consultarPersona(
        @WebParam(name = "ConsultarPersonaRequest", targetNamespace = "http://ubicuo.com.pe/eai/ebs/services/SpringTypeBDWS/types", partName = "request")
        ConsultarPersonaRequest request);

}
